In [27]:
import numpy as np
import matplotlib.pyplot as mtp
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [10]:
dataset=pd.read_csv('/content/healthcare_dataset.csv')

In [77]:
x=dataset.iloc[:,[1,8]].values
x

array([[3.00000000e+01, 1.88562813e+04],
       [6.20000000e+01, 3.36433273e+04],
       [7.60000000e+01, 2.79550961e+04],
       ...,
       [3.80000000e+01, 2.76207647e+04],
       [4.30000000e+01, 3.24510924e+04],
       [5.30000000e+01, 4.01013417e+03]])

In [43]:
y=dataset.iloc[:, 13].values
y

array(['Normal', 'Inconclusive', 'Normal', ..., 'Abnormal', 'Abnormal',
       'Abnormal'], dtype=object)

In [45]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [49]:
print(x_train)
print(x_test)

[[ 0.84002493 -0.35792544]
 [-0.18129726  0.20208308]
 [-1.04942113  1.49109451]
 ...
 [ 0.48256216  1.41201981]
 [ 1.7081488  -1.30454007]
 [-0.79409058  1.30814293]]
[[-0.69195836  0.68217243]
 [-0.02809894  1.65770452]
 [ 1.35068603  0.00986923]
 ...
 [ 0.6868266  -0.30587593]
 [ 0.84002493  0.53913416]
 [-0.84515669  0.42376296]]


In [46]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [50]:
print(x_test)

[[-0.69195836  0.68217243]
 [-0.02809894  1.65770452]
 [ 1.35068603  0.00986923]
 ...
 [ 0.6868266  -0.30587593]
 [ 0.84002493  0.53913416]
 [-0.84515669  0.42376296]]


In [47]:
y_pred=classifier.predict(x_test)
y_pred

array(['Abnormal', 'Inconclusive', 'Abnormal', ..., 'Abnormal',
       'Abnormal', 'Abnormal'], dtype='<U12')

In [48]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[2706,  109, 1846],
       [2692,  104, 1819],
       [2680,  116, 1803]])

In [81]:
y_pred=classifier.predict([[0.69195836,-1.68217243]])
print(y_pred)

['Normal']


In [76]:
y_pred=classifier.predict([[0.99195836,0.95217243]])
print(y_pred)

['Abnormal']


In [80]:
y_pred=classifier.predict([[0.69195836,1.68217243]])
print(y_pred)

['Inconclusive']
